export const actionTypes = {

  MAINMENU_START_FETCHING: 'MAINMENU_START_FETCHING',
  MAINMENU_FETCHED: 'MAINMENU_FETCHED',
  MAINMENU_FETCH_ERROR: 'MAINMENU_FETCH_ERROR',

  HOME_START_FETCHING: 'HOME_START_FETCHING',
  HOME_FETCHED: 'HOME_FETCHED',
  HOME_FETCH_ERROR: 'HOME_FETCH_ERROR',

  TOUR_START_FETCHING: 'TOUR_START_FETCHING',
  TOUR_FETCHED: 'TOUR_FETCHED',
  TOUR_FETCH_ERROR: 'TOUR_FETCH_ERROR',

  NEWS_START_FETCHING: 'NEWS_START_FETCHING',
  NEWS_FETCHED: 'NEWS_FETCHED',
  NEWS_FETCH_ERROR: 'NEWS_FETCH_ERROR',

  ABOUT_START_FETCHING: 'ABOUT_START_FETCHING',
  ABOUT_FETCHED: 'ABOUT_FETCHED',
  ABOUT_FETCH_ERROR: 'ABOUT_FETCH_ERROR',

  GALLERY_START_FETCHING: 'GALLERY_START_FETCHING',
  GALLERY_FETCHED: 'GALLERY_FETCHED',
  GALLERY_FETCH_ERROR: 'GALLERY_FETCH_ERROR',

  MUSIC_START_FETCHING: 'MUSIC_START_FETCHING',
  MUSIC_FETCHED: 'MUSIC_FETCHED',
  MUSIC_FETCH_ERROR: 'MUSIC_FETCH_ERROR',

  MEDIA_AUDIO_START_FETCHING: 'MEDIA_AUDIO_START_FETCHING',
  MEDIA_AUDIO_FETCHED: 'MEDIA_AUDIO_FETCHED',
  MEDIA_AUDIO_FETCH_ERROR: 'MEDIA_AUDIO_FETCH_ERROR',

  MEDIA_IMAGE_START_FETCHING: 'MEDIA_IMAGE_START_FETCHING',
  MEDIA_IMAGE_FETCHED: 'MEDIA_IMAGE_FETCHED',
  MEDIA_IMAGE_FETCH_ERROR: 'MEDIA_IMAGE_FETCH_ERROR',

  MEDIA_REMOTE_VIDEO_START_FETCHING: 'MEDIA_REMOTE_VIDEO_FETCHING',
  MEDIA_REMOTE_VIDEO_FETCHED: 'MEDIA_REMOTE_VIDEO_FETCHED',
  MEDIA_REMOTE_VIDEO_FETCH_ERROR: 'MEDIA_REMOTE_VIDEO_FETCH_ERROR',

  BASIC_CONTACT_FORM_START_FETCHING: 'BASIC_CONTACT_FORM_FETCHING',
  BASIC_CONTACT_FORM_FETCHED: 'BASIC_CONTACT_FORM_FETCHED',
  BASIC_CONTACT_FORM_FETCH_ERROR: 'BASIC_CONTACT_FORM_FETCH_ERROR',

}