export const actionTypes = {

  MAINMENU_START_FETCHING: 'MAINMENU_START_FETCHING',
  MAINMENU_FETCHED: 'MAINMENU_FETCHED',
  MAINMENU_FETCH_ERROR: 'MAINMENU_FETCH_ERROR',

  HOME_START_FETCHING: 'HOME_START_FETCHING',
  HOME_FETCHED: 'HOME_FETCHED',
  HOME_FETCH_ERROR: 'HOME_FETCH_ERROR',

  TOUR_START_FETCHING: 'TOUR_START_FETCHING',
  TOUR_FETCHED: 'TOUR_FETCHED',
  TOUR_FETCH_ERROR: 'TOUR_FETCH_ERROR',


}